import { Preset } from '../../types';

export const DEFAULT_PRESETS: Preset[] = [
  {
    id: 'fine-squiggle',
    name: 'Fine Ink Squiggle',
    description: 'High-density horizontal scanlines with delicate frequency & amplitude modulation.',
    category: 'plotter',
    filters: {
      brightness: 10,
      contrast: 25,
      gamma: 1.0,
      invert: false,
      blurRadius: 1.5,
      thresholdEnabled: false,
      edgeDetection: true,
      edgeBlend: 0.25,
    },
    algorithm: {
      type: 'squiggle',
      squiggle: {
        lineSpacing: 1.8,
        maxAmplitude: 2.2,
        minFrequency: 0.15,
        maxFrequency: 1.8,
        angle: 0,
        waveType: 'sine',
        serpentine: true,
        phaseShift: 0,
      },
      crosshatch: {
        lineSpacing: 2.0,
        angles: [45, 135, 0, 90],
        thresholds: [220, 160, 100, 50],
        numLayers: 3,
        serpentine: true,
        wobble: 0.2,
        segmentLength: 0.6,
      },
      spiral: {
        ringSpacing: 1.5,
        maxWaveAmplitude: 1.6,
        angularResolution: 180,
        direction: 'outward',
        centerX: 0,
        centerY: 0,
        frequencyModulation: 1.2,
      },
      stippleTsp: {
        pointCount: 2500,
        samplingMode: 'error-diffusion',
        tspIterations: 8,
        connectMode: 'tsp-tour',
        dotRadius: 0.4,
        invertedDensity: false,
      },
      contours: {
        levels: 16,
        minLuminance: 20,
        maxLuminance: 235,
        smoothing: 2,
      },
      flowfield: {
        streamSpacing: 1.4,
        stepLength: 0.8,
        maxSteps: 60,
        noiseScale: 1.0,
        directionMode: 'gradient',
      },
    },
    optimization: {
      enableRDP: true,
      rdpTolerance: 0.08,
      enablePathSorting: true,
      enablePathReversal: true,
      removeShortPaths: true,
      minPathLengthMm: 0.4,
    },
  },
  {
    id: 'arch-crosshatch',
    name: 'Architectural Cross-Hatch',
    description: 'Multi-layer 4-pass cross-hatching reproducing vintage copperplate engravings.',
    category: 'artistic',
    filters: {
      brightness: 5,
      contrast: 30,
      gamma: 1.1,
      invert: false,
      blurRadius: 1.0,
      thresholdEnabled: false,
      edgeDetection: true,
      edgeBlend: 0.35,
    },
    algorithm: {
      type: 'crosshatch',
      squiggle: {
        lineSpacing: 2.0,
        maxAmplitude: 2.5,
        minFrequency: 0.2,
        maxFrequency: 2.0,
        angle: 0,
        waveType: 'sine',
        serpentine: true,
        phaseShift: 0,
      },
      crosshatch: {
        lineSpacing: 1.6,
        angles: [45, 135, 0, 90],
        thresholds: [210, 150, 95, 45],
        numLayers: 4,
        serpentine: true,
        wobble: 0.15,
        segmentLength: 0.5,
      },
      spiral: {
        ringSpacing: 1.8,
        maxWaveAmplitude: 1.8,
        angularResolution: 180,
        direction: 'outward',
        centerX: 0,
        centerY: 0,
        frequencyModulation: 1.0,
      },
      stippleTsp: {
        pointCount: 3000,
        samplingMode: 'rejection',
        tspIterations: 10,
        connectMode: 'tsp-tour',
        dotRadius: 0.4,
        invertedDensity: false,
      },
      contours: {
        levels: 14,
        minLuminance: 25,
        maxLuminance: 230,
        smoothing: 2,
      },
      flowfield: {
        streamSpacing: 1.5,
        stepLength: 0.8,
        maxSteps: 50,
        noiseScale: 1.0,
        directionMode: 'gradient',
      },
    },
    optimization: {
      enableRDP: true,
      rdpTolerance: 0.1,
      enablePathSorting: true,
      enablePathReversal: true,
      removeShortPaths: true,
      minPathLengthMm: 0.5,
    },
  },
  {
    id: 'continuous-spiral',
    name: 'Continuous Archimedean Spiral',
    description: 'Single continuous unbroken stroke from center to edge (zero pen lifts!).',
    category: 'minimalist',
    filters: {
      brightness: 15,
      contrast: 35,
      gamma: 1.0,
      invert: false,
      blurRadius: 2.0,
      thresholdEnabled: false,
      edgeDetection: false,
      edgeBlend: 0.2,
    },
    algorithm: {
      type: 'spiral',
      squiggle: {
        lineSpacing: 2.0,
        maxAmplitude: 2.0,
        minFrequency: 0.2,
        maxFrequency: 2.0,
        angle: 0,
        waveType: 'sine',
        serpentine: true,
        phaseShift: 0,
      },
      crosshatch: {
        lineSpacing: 2.0,
        angles: [45, 135],
        thresholds: [180, 100],
        numLayers: 2,
        serpentine: true,
        wobble: 0,
        segmentLength: 0.6,
      },
      spiral: {
        ringSpacing: 1.2,
        maxWaveAmplitude: 1.4,
        angularResolution: 240,
        direction: 'outward',
        centerX: 0,
        centerY: 0,
        frequencyModulation: 1.5,
      },
      stippleTsp: {
        pointCount: 2000,
        samplingMode: 'error-diffusion',
        tspIterations: 8,
        connectMode: 'tsp-tour',
        dotRadius: 0.4,
        invertedDensity: false,
      },
      contours: {
        levels: 12,
        minLuminance: 30,
        maxLuminance: 220,
        smoothing: 2,
      },
      flowfield: {
        streamSpacing: 1.5,
        stepLength: 0.8,
        maxSteps: 50,
        noiseScale: 1.0,
        directionMode: 'gradient',
      },
    },
    optimization: {
      enableRDP: true,
      rdpTolerance: 0.05,
      enablePathSorting: false,
      enablePathReversal: false,
      removeShortPaths: false,
      minPathLengthMm: 0.1,
    },
  },
  {
    id: 'axidraw-tsp',
    name: 'AxiDraw Stipple TSP Tour',
    description: '3,000 luminance-weighted stipple dots connected into a continuous 2-opt TSP path.',
    category: 'plotter',
    filters: {
      brightness: 10,
      contrast: 30,
      gamma: 1.0,
      invert: false,
      blurRadius: 1.5,
      thresholdEnabled: false,
      edgeDetection: true,
      edgeBlend: 0.2,
    },
    algorithm: {
      type: 'stipple-tsp',
      squiggle: {
        lineSpacing: 2.0,
        maxAmplitude: 2.0,
        minFrequency: 0.2,
        maxFrequency: 2.0,
        angle: 0,
        waveType: 'sine',
        serpentine: true,
        phaseShift: 0,
      },
      crosshatch: {
        lineSpacing: 2.0,
        angles: [45, 135],
        thresholds: [180, 100],
        numLayers: 2,
        serpentine: true,
        wobble: 0,
        segmentLength: 0.6,
      },
      spiral: {
        ringSpacing: 1.5,
        maxWaveAmplitude: 1.5,
        angularResolution: 180,
        direction: 'outward',
        centerX: 0,
        centerY: 0,
        frequencyModulation: 1.0,
      },
      stippleTsp: {
        pointCount: 3200,
        samplingMode: 'error-diffusion',
        tspIterations: 12,
        connectMode: 'tsp-tour',
        dotRadius: 0.4,
        invertedDensity: false,
      },
      contours: {
        levels: 12,
        minLuminance: 30,
        maxLuminance: 220,
        smoothing: 2,
      },
      flowfield: {
        streamSpacing: 1.5,
        stepLength: 0.8,
        maxSteps: 50,
        noiseScale: 1.0,
        directionMode: 'gradient',
      },
    },
    optimization: {
      enableRDP: false,
      rdpTolerance: 0.05,
      enablePathSorting: false,
      enablePathReversal: false,
      removeShortPaths: false,
      minPathLengthMm: 0.1,
    },
  },
  {
    id: 'topo-contours',
    name: 'Topographic Contours',
    description: 'Smooth marching squares iso-luminance elevation contours.',
    category: 'artistic',
    filters: {
      brightness: 10,
      contrast: 20,
      gamma: 1.1,
      invert: false,
      blurRadius: 3.0,
      thresholdEnabled: false,
      edgeDetection: false,
      edgeBlend: 0,
    },
    algorithm: {
      type: 'contours',
      squiggle: {
        lineSpacing: 2.0,
        maxAmplitude: 2.0,
        minFrequency: 0.2,
        maxFrequency: 2.0,
        angle: 0,
        waveType: 'sine',
        serpentine: true,
        phaseShift: 0,
      },
      crosshatch: {
        lineSpacing: 2.0,
        angles: [45, 135],
        thresholds: [180, 100],
        numLayers: 2,
        serpentine: true,
        wobble: 0,
        segmentLength: 0.6,
      },
      spiral: {
        ringSpacing: 1.5,
        maxWaveAmplitude: 1.5,
        angularResolution: 180,
        direction: 'outward',
        centerX: 0,
        centerY: 0,
        frequencyModulation: 1.0,
      },
      stippleTsp: {
        pointCount: 2000,
        samplingMode: 'error-diffusion',
        tspIterations: 8,
        connectMode: 'tsp-tour',
        dotRadius: 0.4,
        invertedDensity: false,
      },
      contours: {
        levels: 18,
        minLuminance: 15,
        maxLuminance: 240,
        smoothing: 3,
      },
      flowfield: {
        streamSpacing: 1.5,
        stepLength: 0.8,
        maxSteps: 50,
        noiseScale: 1.0,
        directionMode: 'gradient',
      },
    },
    optimization: {
      enableRDP: true,
      rdpTolerance: 0.12,
      enablePathSorting: true,
      enablePathReversal: true,
      removeShortPaths: true,
      minPathLengthMm: 1.0,
    },
  },
];
