import { Path, PhysicalDimensions } from '../../types';

export interface SvgExportOptions {
  dimensions: PhysicalDimensions;
  strokeColor?: string;
  strokeWidthMm?: number;
  includeRapidTravel?: boolean;
  decimalPlaces?: number;
}

/**
 * Generate Plotter-Ready SVG with mm units and pure M/L commands
 */
export function exportToSVG(paths: Path[], options: SvgExportOptions): string {
  const { dimensions, strokeColor = '#000000', strokeWidthMm = 0.3, includeRapidTravel = false, decimalPlaces = 2 } = options;

  let widthMm = dimensions.paperSize === 'Custom' ? dimensions.customWidthMm : 210;
  let heightMm = dimensions.paperSize === 'Custom' ? dimensions.customHeightMm : 297;

  if (dimensions.paperSize === 'A4') {
    widthMm = dimensions.orientation === 'landscape' ? 297 : 210;
    heightMm = dimensions.orientation === 'landscape' ? 210 : 297;
  } else if (dimensions.paperSize === 'A3') {
    widthMm = dimensions.orientation === 'landscape' ? 420 : 297;
    heightMm = dimensions.orientation === 'landscape' ? 297 : 420;
  } else if (dimensions.paperSize === 'A5') {
    widthMm = dimensions.orientation === 'landscape' ? 210 : 148;
    heightMm = dimensions.orientation === 'landscape' ? 148 : 210;
  } else if (dimensions.paperSize === 'Letter') {
    widthMm = dimensions.orientation === 'landscape' ? 279.4 : 215.9;
    heightMm = dimensions.orientation === 'landscape' ? 215.9 : 279.4;
  } else if (dimensions.paperSize === 'Square') {
    widthMm = 200;
    heightMm = 200;
  }

  const fmt = (num: number) => num.toFixed(decimalPlaces);

  // Generate pure M and L path data
  let drawPathData = '';
  for (const path of paths) {
    if (path.length < 2) continue;
    drawPathData += `M ${fmt(path[0][0])} ${fmt(path[0][1])} `;
    for (let i = 1; i < path.length; i++) {
      drawPathData += `L ${fmt(path[i][0])} ${fmt(path[i][1])} `;
    }
  }

  let travelPathData = '';
  if (includeRapidTravel && paths.length > 1) {
    for (let i = 0; i < paths.length - 1; i++) {
      const pEnd = paths[i][paths[i].length - 1];
      const pNextStart = paths[i + 1][0];
      travelPathData += `M ${fmt(pEnd[0])} ${fmt(pEnd[1])} L ${fmt(pNextStart[0])} ${fmt(pNextStart[1])} `;
    }
  }

  const svgLines: string[] = [
    `<?xml version="1.0" encoding="UTF-8" standalone="no"?>`,
    `<svg width="${widthMm}mm" height="${heightMm}mm" viewBox="0 0 ${widthMm} ${heightMm}" version="1.1" xmlns="http://www.w3.org/2000/svg">`,
    `  <!-- Generated by VectorPlotter CAM (CAM-Ready Vector Artwork) -->`,
    `  <desc>Units: Millimeters (mm), Width: ${widthMm}mm, Height: ${heightMm}mm, Paths: ${paths.length}</desc>`,
    `  <g id="plotter_artwork" fill="none" stroke="${strokeColor}" stroke-width="${strokeWidthMm}mm" stroke-linecap="round" stroke-linejoin="round">`,
    `    <path d="${drawPathData.trim()}" />`,
    `  </g>`,
  ];

  if (includeRapidTravel && travelPathData) {
    svgLines.push(
      `  <g id="pen_up_travel" fill="none" stroke="#ff3d71" stroke-width="0.15mm" stroke-dasharray="1.5,1.5" opacity="0.6">`,
      `    <path d="${travelPathData.trim()}" />`,
      `  </g>`
    );
  }

  svgLines.push(`</svg>`);
  return svgLines.join('\n');
}
